### PR TITLE
Add panlint tests

### PR DESCRIPTION
**Pull request by stdweird**

### CODE REVIEW

**Comment by stdweird** [comment]
@jrha do you know what is required at travis side to make this work?

**Comment by jrha** [comment]
Nothing, in theory, the repository is already enabled.

**Comment by jrha** [comment]
But I think it will only see the mitaka branch at the moment.

**Comment by stdweird** [comment]
https://docs.travis-ci.com/user/customizing-the-build#Building-Specific-Branches
"Note that for historical reasons .travis.yml needs to be present on all active branches of your project."

So we should merge this and cherry-pick in all other branches?

**Comment by jrha** [comment]
Sounds like a plan

**Pull request merged**
