### PR TITLE
Templates for OpenStack Xena version

### PR DESCRIPTION
**Pull request by jouvin**
- Have been used successfully at IJCLab

### CODE REVIEW

**Comment by jouvin** [comment]
@jrha I added the changes required for Xena support. But a few check errors remain and I don't know how to fix them. Your help would be very much appreciated!

- 2 lines too long where I don't know what is the recommended way to split them
- 1 URL ending by a `/` where the `/` is explicitely required
- 1 indentation issue where I tend to consider that my version is the right one!

**Comment by jrha** [comment]
> 2 lines too long where I don't know what is the recommended way to split them

There's no way to shorten them, you can ignore the warnings until I have the time to finish test suppression in panlint, you could add `# panlint disable=LP006` to the line before them in anticipation of this if you want.

> 1 URL ending by a / where the / is explicitly required

Same as above, `# panlint disable=PP001` for this one.

> 1 indentation issue where I tend to consider that my version is the right one!

Yep, that looks like a bug in the indent checker.

**Comment by jouvin** [comment]
I tried your suggestions but it seems it didn't help... This is in `features/keystone/config.pan` and `features/neutron/agents/linuxbridge_agent.pan`

**Comment by jrha** [comment]
Thanks, the version of panlint the tests use doesn't have this feature yet.

**Review by jrha — APPROVED** [review]

**Comment by jrha** [comment]
Found the bug in the indenter and fixed it here: https://github.com/stfc/Pan-Indenter/pull/2

**Comment by jouvin** [comment]
I tried to rerun the indent check but it is still failing. Not sure if it is expected. And there is a "file not found" error for a file deleted in the last modifications, Not related to the indent checker itself but to the way we construct the list of files to check... I'll try to look at it.

**Comment by jrha** [comment]
The `git diff` needs `--diff-filter=d` adding

**Pull request merged**
