### PR TITLE
Split init script

### PR DESCRIPTION
**Pull request by apdibbo**
Create helper scripts to be used when initializing each component

Split init script so there is one per component to make the scripts more modular

### CODE REVIEW

**Comment by guillaume-philippon** [comment]
Same here. No mergeable

**Comment by apdibbo** [comment]
resolve conflicts

**Comment by jouvin** [comment]
Any reason to postpone merging furthermore?

**Comment by apdibbo** [comment]
I see no reason to, @guillaume-philippon are you happy to merge this?

**Comment by jrha** [comment]
@guillaume-philippon _poke_

**Comment by jouvin** [comment]
Guillaume pinged offline!!!

**Pull request merged**
